### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by LarsRefsgaard** [hughsk/flat#119]
Please add this module to deno on deno.land/x

**Comment by Soremwar** [comment]
Don't know if it's a joke, but this is already available through NPM compatibility

```js
import {flatten} from "https://cdn.skypack.dev/flat@5.0.2";

const flattened = flatten({
    key1: {
        keyA: 'valueI'
    },
    key2: {
        keyB: 'valueII'
    },
    key3: { a: { b: { c: 2 } } }
});

console.log(flattened);
// {
//   'key1.keyA': 'valueI',
//   'key2.keyB': 'valueII',
//   'key3.a.b.c': 2
// }
```

**Comment by jonkoops** [comment]
There is currently no intention to publish this module directly for Deno (disregarding the fact someone already claimed [`flat`](https://deno.land/x/flat)). Like mentioned before this package can be loaded from any 3rd party CDN that uses the NPM registry.

That said, the next version will land extra bits to better support ES modules and TypeScript support. Which should help with Deno as well. Especially since Deno has recently [announced compatibility](https://deno.com/blog/changes#compatibility-with-node-and-npm) with NPM.
