### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by yuchuan1** [hughsk/flat#171]
In my nx monorepo angular project, i got the following error after upgrading to 6.0.0 from 5.0.2

Jest 29.7.0
Falt 6.0.0

 Test suite failed to run
       
           Jest encountered an unexpected token

Details:
/node_modules/.pnpm/flat@6.0.0/node_modules/flat/index.d.ts:1
           ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export interface FlattenOptions {
                                                                                                                                                               ^^^^^^
       
           SyntaxError: Unexpected token 'export'

**Comment by jonkoops** [comment]
This is expected, as the [release notes](https://github.com/hughsk/flat/releases) state the package is now distributed in the [ECMAScript module format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). You can read about how to use Jest with this format in [their documentation](https://jestjs.io/docs/ecmascript-modules).

**Comment by muhammedgaygisiz** [comment]
Since i struggled with the same issue and it is extremely annoying everytime i run into the problem, a quick possibility to fix/get around the issue:

- Create a mock folder "__mocks__" adjacent to node modules
- Add 

roots: ['<rootDir>', path.resolve(__dirname, './__mocks__')]

to your jest.preset.js file.

- Create a folder named "flat" in the "__mocks__" folder and an empty file named "index.ts" within it

 That's how it worked for me. Hope it helps @yuchuan1

**Comment by yuchuan1** [comment]
> Since i struggled with the same issue and it is extremely annoying everytime i run into the problem, a quick possibility to fix/get around the issue:
> 
> * Create a mock folder "**mocks**" adjacent to node modules
> * Add
> 
> roots: ['', path.resolve(__dirname, './**mocks**')]
> 
> to your jest.preset.js file.
> 
> * Create a folder named "flat" in the "**mocks**" folder and an empty file named "index.ts" within it
> 
> That's how it worked for me. Hope it helps @yuchuan1

Tried it but it didnt work.
my jest.preset looks like this
```
const nxPreset = require('@nx/jest/preset').default;
const path = require('path');

module.exports = {
   globalSetup: './jestGlobalSetup.js',
  ...nxPreset,
 roots: ['', path.resolve(__dirname, './mocks')],
  snapshotFormat: { escapeString: true, printBasicPrototype: true },
  resolver: path.resolve(__dirname, 'ag-grid-resolver.js')
};
```

**Comment by FabienDehopre** [comment]
> Since i struggled with the same issue and it is extremely annoying everytime i run into the problem, a quick possibility to fix/get around the issue:
> 
> * Create a mock folder "**mocks**" adjacent to node modules
> * Add
> 
> roots: ['', path.resolve(__dirname, './**mocks**')]
> 
> to your jest.preset.js file.
> 
> * Create a folder named "flat" in the "**mocks**" folder and an empty file named "index.ts" within it
> 
> That's how it worked for me. Hope it helps @yuchuan1

I tried this solution as well but it does not work. As @yuchuan1 I'm using nx and, unfortunately, the proposed solution does not work.

**Comment by fappaz** [comment]
None of the solutions on  [this SO thread](https://stackoverflow.com/a/77321163/2516673) solved the issue, so I decided to downgrade the package back to v5.

**Comment by DaSchTour** [comment]
So what is a viable solution to this issue? I have an NX workspace which from the comments doesn't allow to apply the mentioned solutions. This package is also just a dependency for another package I use (@ngneat/transloco) which updated to the new version. So in the end this package moving to ESM only holds me back from updating NX and Angular to newer versions just because I used @ngneat/transloco. I'm pretty sure this kind of issues will make a lot of developers dislike the JavaScript ecosystem even more. While I don't want to blame the maintainers of this package as I see they have valid reasons for their change. I really hat the current state we are in with this CJS to ESM transition and the ugly behavior of node.js. The worst thing about this, that these issues regularly pop up since years and I would have hoped that it will get better. But there is no improvement in this situation on the horizon.

**Comment by Litarvan** [comment]
I managed to make the solution work by calling the 'mocks' folder `__mocks__` instead since setting `roots` in my Jest config did not work; though a blanket mock will probably create errors when transloco will try to use functions from flat (but at least we have working tests for now).

Since using Jest ES Modules does not work well with a lot of dependencies (which is understandable since the support from Jest is still experimental), it was the only way to make it work :/

Thanks a lot for the mock solution, was the first one that worked after days of debugging

**Comment by terrynguyen255** [comment]
Only mocking `flat` can fix the issue for me but that approach is too harsh. So unfortunately, I had to switch to another package [flat-obj](https://www.npmjs.com/package/flat-obj)
